ecommerce/routes/web.php
<?php

use App\Http\Controllers\PdfController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route Halaman User
Route::get('/user-page', function () {
     return view('pages.user.home');
});

Route::middleware(['auth'])->group(function () {
    // Route Halaman Admin
Route::get('/admin2', function () {
    return view('pages.admin.index');
});
// Route CRUD Produk
Route::resource('product','ProductsController');

// Route CRUD Toko
Route::resource('shop', 'ShopsController');

// Route CRUD Kategori
Route::resource('categorie', 'CategorieController');

// Route CRUD Order
Route::resource('order', 'OrdersController');

//Route Transaction
Route::get('/transaction', function () {
    return view('pages.admin.transaction.index');
});

});

// Route Halaman Utama
Route::get('/', function () {
    return view('welcome');
});

//Route untuk DomPDF Package

Route::get('/view-statement', function () {
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Laravel E-Commerce Project</h1>');
    return $pdf->stream();
});

Route::get('/statement','PdfController@test');

//Route Authentication

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route TinyMCE

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

ecommerce/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile() {
        return $this->hasOne('App\Profile','user_id');
    }

    public function orders() {
        return $this->hasMany('App\Order','user_id');
    }
}

ecommerce/resources/views/includes/user/footer.blade.php
<footer class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="footer-left">
                    <div class="footer-logo">
                        <a href="#"><img src="{{asset('user/img/footer-logo.png')}}" alt="" /></a>
                    </div>
                    <ul>
                        <li>Alamat: Jl Rasuna Said No 20 Jakarta Pusat</li>
                        <li>Telepon: +62 11.188.888</li>
                        <li>Email: hello.shayna@gmail.com</li>
                    </ul>
                    <div class="footer-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1">
                <div class="footer-widget">
                    <h5>Informasi</h5>
                    <ul>
                        <li><a href="#">Tentang Kami</a></li>
                        <li><a href="#">Checkout</a></li>
                        <li><a href="#">Kontak</a></li>
                        <li><a href="#">Layanan</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="footer-widget">
                    <h5>Akun</h5>
                    <ul>
                        <li><a href="#">Akun Saya</a></li>
                        <li><a href="#">Kontak</a></li>
                        <li><a href="#">Keranjang Belanja</a></li>
                        <li><a href="#">Toko</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-reserved">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright-text">
                        Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        All rights reserved | Shayna
                    </div>
                    <div class="payment-pic">
                        <img src="{{asset('user/img/payment-method.png')}}" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

ecommerce/resources/views/includes/user/header.blade.php
<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class=" fa fa-user"></i>
                    Hello, {{ Auth::user()->name }}
                </div>
                <div class="phone-service">
                    <i class=" fa fa-square"></i>
                    {{ Auth::user()->email }}
                </div>
            </div>
            <div class="ht-right">
                <a href="/home" class="login-panel">Home</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <a href="./index.html">
                            <img src="{{asset('user/img/logo.png')}}" alt="" />
                        </a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-7"></div>
                <div class="col-lg-3 text-right col-md-3">
                    <ul class="nav-right">
                        <li class="cart-icon">
                            Keranjang Belanja &nbsp;
                            <a href="#">
                                <i class="icon_bag_alt"></i>
                            </a>
                            <div class="cart-hover">
                                
                                <div class="select-button">
                                    <a href="{{route('order.create')}}" class="primary-btn view-card">BUAT ORDER</a>
                                    <a href="{{route('order.index')}}" class="primary-btn checkout-btn">TRANSAKSI</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

ecommerce/resources/views/includes/user/script.blade.php
<!-- Js Plugins -->
<script src="{{ asset('user/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('user/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('user/js/jquery-ui.min.js') }}"></script>
<script src="{{ asset('user/js/jquery.countdown.min.js') }}"></script>
<script src="{{ asset('user/js/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('user/js/jquery.zoom.min.js') }}"></script>
<script src="{{ asset('user/js/jquery.dd.min.js') }}"></script>
<script src="{{ asset('user/js/jquery.slicknav.js') }}"></script>
<script src="{{ asset('user/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('user/js/main.js') }}"></script>

ecommerce/resources/views/includes/user/style.blade.php
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet" />

<!-- Css Styles -->
<link rel="stylesheet" href="{{ asset('user/css/bootstrap.min.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ asset('user/css/font-awesome.min.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ asset('user/css/themify-icons.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ asset('user/css/elegant-icons.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ asset('user/css/owl.carousel.min.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ asset('user/css/nice-select.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ asset('user/css/jquery-ui.min.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ asset('user/css/slicknav.min.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ asset('user/css/style.css') }}" type="text/css" />